# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "20cf92c8f6882a0a10242fac8b51b74fa55dbfe1"

[[deps.Entanglement]]
path = "."
uuid = "58b4d12d-b8b9-461e-9ba3-5cc1fd6afe1b"
version = "1.0.0-DEV"
