name = "BB84_Protocol"
uuid = "66345eaa-12ed-4c96-9a3f-b58dc8a2411e"
version = "1.0.0-DEV"
authors = ["carlomazzanti"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
GLMakie = "0.13.8"
Statistics = "1.11.1"
julia = "1.12.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
