name = "BB84_Protocol"
uuid = "66345eaa-12ed-4c96-9a3f-b58dc8a2411e"
authors = ["carlomazzanti"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
